set(CPACK_GENERATOR DEB)
set(CPACK_INSTALL_DEFAULT_DIRECTORY_PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
set(CPACK_PACKAGE_NAME jarvis)
set(CPACK_PACKAGE_VENDOR Bohdan99py)
set(CPACK_PACKAGE_CONTACT "Bohdan99py <Bohdan99py@users.noreply.github.com>")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Jarvis desktop AI assistant with voice, skills and quick commands")
set(CPACK_PACKAGE_VERSION "${PROJECT_VERSION}")
set(CPACK_PACKAGING_INSTALL_PREFIX /usr)
set(CPACK_DEBIAN_PACKAGE_SECTION utils)
set(CPACK_DEBIAN_PACKAGE_PRIORITY optional)
set(CPACK_DEBIAN_PACKAGE_HOMEPAGE "https://github.com/Bohdan99py/jarvis-kubuntu")
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)
set(CPACK_DEBIAN_PACKAGE_DEPENDS "qml6-module-qtquick, qml6-module-qtquick-controls, qml6-module-qtquick-layouts, qml6-module-qtquick-templates, qml6-module-qtquick-window, qml6-module-qtquick-dialogs, qml6-module-qtqml-workerscript, qml6-module-qt-labs-platform, python3, python3-venv, python3-speechd, alsa-utils, speech-dispatcher, speech-dispatcher-espeak-ng, espeak-ng, ca-certificates, systemd, dbus")
set(CPACK_DEBIAN_PACKAGE_RECOMMENDS "plasma-discover, desktop-file-utils")
set(CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA "${CMAKE_CURRENT_SOURCE_DIR}/packaging/postinst;${CMAKE_CURRENT_SOURCE_DIR}/packaging/prerm")
set(CPACK_DEBIAN_PACKAGE_CONTROL_STRICT_PERMISSION ON)
execute_process(COMMAND dpkg --print-architecture OUTPUT_VARIABLE JARVIS_ARCH OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "${JARVIS_ARCH}")
if(NOT JARVIS_DISTRO)
    file(STRINGS /etc/os-release JARVIS_OS_LINE REGEX "^VERSION_ID=")
    string(REGEX REPLACE "^VERSION_ID=\"?([^\"]+)\"?$" "\\1" JARVIS_OS_VERSION "${JARVIS_OS_LINE}")
    set(JARVIS_DISTRO "ubuntu-${JARVIS_OS_VERSION}")
endif()
set(CPACK_PACKAGE_FILE_NAME "jarvis_${PROJECT_VERSION}_${JARVIS_DISTRO}_${JARVIS_ARCH}")
include(CPack)
